before_script:
  - export BRANCH_TAG=$(echo $CI_COMMIT_REF_NAME | sed "s/\//_/g")
  - export ENV_NAME=$(echo ${BRANCH_TAG} | awk '{print tolower($0)}')
  - export GOOGLE_APPLICATION_CREDENTIALS=/path/to/sac

stages:
  - build
  - test
  - deploy

unit_test:
  stage: test
  image: node:12
  tags:
    - k8s
  script:
    - npm install
    - npm test

integration_test:
  stage: test
  image: python:3.8
  tags:
    - k8s
  script:
    - pip install pytest pandas google-cloud-bigquery
    - pytest test/*.py 

build:
  stage: build
  image: node:12
  tags:
    - k8s
  script:
    - export NODE_ENV=production
    - export NO_SOURCEMAPS=true
    - export CI=false # prevent build crash if any warnings
    - npm install
    - npm install -g webpack webpack-cli
    - webpack

  artifacts:
    expire_in: 1 week
    paths:
      - ./

deploy:
  stage: deploy
  image: python:3.8
  tags:
    - k8s
  script:
    - pip install pytest pandas google-cloud-bigquery google-cloud-storage envsubst
    - python deploy.py
