 language: node_js
 node_js:
   - "12"

before_script:
  - npm install webpack webpack-cli -g

script: webpack -p

deploy:
  provider: pages
  target_branch: webpack
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: Travis Webpack
  on:
    branch: master
