language: node_js
 node_js:
   - "12"

script:
    - npm install
    - npm test

script:
    - export NODE_ENV=production
    - export NO_SOURCEMAPS=true
    - export CI=false # prevent build crash if any warnings
    - npm install
    - npm install -g webpack webpack-cli
    - webpack
    

deploy:
  provider: pages
  target_branch: webpack
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  name: Travis Webpack
  on:
    branch: master
